CREATE DATABASE mountain_guide;

CREATE ROLE admin_role CREATEDB CREATEROLE NOINHERIT;
CREATE ROLE rw_role NOINHERIT;
CREATE ROLE ro_role NOINHERIT;

CREATE ROLE mg_admin LOGIN PASSWORD 'password' INHERIT;
CREATE ROLE mg_rw LOGIN PASSWORD 'password' INHERIT;
CREATE ROLE mg_ro LOGIN PASSWORD 'password' INHERIT;

REVOKE ALL ON SCHEMA public FROM public;
REVOKE ALL ON SCHEMA public FROM admin_role;
REVOKE ALL ON SCHEMA public FROM rw_role;
REVOKE ALL ON SCHEMA public FROM ro_role;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ro_role;
GRANT ALL PRIVILEGES ON SCHEMA public TO admin_role;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rw_role, admin_role;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO rw_role, admin_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rw_role, admin_role;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO rw_role, admin_role;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO rw_role, admin_role;

GRANT admin_role TO mg_admin;
GRANT rw_role TO mg_rw;
GRANT ro_role TO mg_ro;
